#!/usr/bin/env python3

import sys

from argparse import ArgumentParser
from helpers import distances, orgdistance


def main():

    # Parse command-line arguments
    parser = ArgumentParser()
    parser.add_argument("FILE1", help="file to compare")
    parser.add_argument("FILE2", help="file to compare")
    args = vars(parser.parse_args())

    # Read files
    try:
        with open(args["FILE1"], "r") as file:
            file1 = file.read()
    except IOError:
        sys.exit(f"Could not read {args['FILE1']}")
    try:
        with open(args["FILE2"], "r") as file:
            file2 = file.read()
    except IOError:
        sys.exit(f"Could not read {args['FILE2']}")



    d = distances(file1, file2)
    orig_matrix = orgdistance(file1, file2)
    original_matrix = [[0 for y in range(len(file2) + 2)] for y in range(len(file1) + 1)]
    for i in range(len(file1)):
        original_matrix[i + 1][0] = file1[i]

    for i in range(len(file1) + 1):
        for j in range(len(file2) + 1):
            original_matrix[i][j + 1] = orig_matrix[i][j]

    original_matrix[0][0] = " "


    for i in range(len(file1) + 1):
        for j in range(len(file2) + 1):
            print("   {}   ".format(original_matrix[i][j]), end="")

        print()


if __name__ == "__main__":
    main()
